version: "3.8"
services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}

  phpmyadmin:
    image: phpmyadmin
    env_file: .env
    ports:
      - 8080:80
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}


  mqtt-server-transfer:
    build: ./mqtt-server-transfer
    depends_on:
      - mysql
    env_file: .env

  server1:
    build: ./server
    restart: always
    depends_on:
      - mysql
      - mosquitto
    env_file: .env
    ports:
      - ${APP_PORT}:${APP_PORT}

  client:
    build: ./client
    ports:
      - 80:80
    env_file: .env

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"  # порт для MQTT
    volumes:
      - ./mqtt-brocker/config:/mosquitto/config
      - ./mqtt-brocker/data:/mosquitto/data
      - ./mqtt-brocker/log:/mosquitto/log
    restart: always
    command: mosquitto -c /mosquitto/config/mosquitto.conf


  device1:
    build: ./device
    environment:
      - DEVICE_ID=device1
    depends_on:
      - mosquitto

  device2:
    build: ./device
    environment:
      - DEVICE_ID=device2
    depends_on:
      - mosquitto


volumes:
  mysql-data:
